In [2]:
a=[1,2,3,4]
print(a,type(a),id(a))

[1, 2, 3, 4] <class 'list'> 2278611547904


In [2]:
import numpy as np

In [4]:
a=[1,2,3,4,5]
np.array(a)

array([1, 2, 3, 4, 5])

In [5]:
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
a.ndim

1

In [7]:
a.shape

(4,)

In [8]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
b.ndim


2

In [10]:
b.shape

(2, 4)

In [11]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
raj=np.array(my_matrix)
raj

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
print(raj)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
np.arange(10,101,10)


array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [14]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
np.linspace(0,5,2)

array([0., 5.])

In [16]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.zeros((3,0))

array([], shape=(3, 0), dtype=float64)

In [18]:
np.zeros((3,))

array([0., 0., 0.])

In [19]:
np.ones((1,))

array([1.])

In [20]:
np.ones((5,))

array([1., 1., 1., 1., 1.])

In [21]:
np.random.randint(10,15)

10

In [22]:
np.random.randint(1,10)

6

In [23]:
np.random .randint(1,10,8)

array([1, 5, 1, 9, 9, 7, 5, 1])

In [24]:
np.random.randn(1,10)

array([[-0.46209057,  1.27804896,  0.11548643, -0.29971942, -0.73094759,
        -0.07971423,  0.88770057,  1.51520973, -0.54026025,  1.04324888]])

In [25]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
#reshape
a=np.arange(25)
print(a,type(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24] <class 'numpy.ndarray'>


In [29]:
a.shape

(25,)

In [30]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
np.arange(15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [35]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
np.arange(15).reshape(3,5).T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [38]:
np.array([[1,2,3],[4,5,6]]).T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [45]:
a=np.array([1,2,3])
b=a
b[0]=100           #shallow copy
print(a)
print(b)
id(a)
id(b)

[100   2   3]
[100   2   3]


2278617732752

In [46]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100           #deep copy
print(a,id(a))
print(b,id(a))

[1 2 3] 2278617734480
[100   2   3] 2278617734480


In [48]:
#sort function
a=np.array([1,2,3,478,56,67,3,357,340])
np.sort(a)

array([  1,   2,   3,   3,  56,  67, 340, 357, 478])

In [53]:
np.sort([3,1,4,2,5,1,5657])

array([   1,    1,    2,    3,    4,    5, 5657])

In [54]:
a=np.array([1,2,3,4])
a=np.append(a,[6,7,8])
print("Numpy array after addition: ",a)

Numpy array after addition:  [1 2 3 4 6 7 8]


In [56]:
a=np.array([1,2,3,4])
a=np.delete(a,2)
print("Numpy array after delete of: ",a)

Numpy array after delete of:  [1 2 4]


In [57]:
a=np.array([5,6,7,8])
a=np.delete(a,0)
print("After delete:",a)

After delete: [6 7 8]


In [59]:
#indexing
a=np.arange(3,10)
print(a)
print(a[6])

[3 4 5 6 7 8 9]
9


In [60]:
a[0]=9
a

array([9, 4, 5, 6, 7, 8, 9])

In [61]:
np.diag(a)

array([[9, 0, 0, 0, 0, 0, 0],
       [0, 4, 0, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 9]])

In [62]:
b=np.arange(0,10)
print(b)
np.diag(b)

[0 1 2 3 4 5 6 7 8 9]


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [68]:
a=np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [69]:
a[2,1]

0

In [73]:
a=np.arange(0,101,10)
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [74]:
a[2]

20

In [75]:
a[[2,3,4,5]]

array([20, 30, 40, 50])

In [79]:
a[[2,3]]=[[29,28]]


In [80]:
a

array([  0,  10,  29,  28,  40,  50,  60,  70,  80,  90, 100])

In [81]:
#mask indexing
a=np.array([15,6,21,16,4])
a

array([15,  6, 21, 16,  4])

In [85]:
a%2==0

array([False,  True, False,  True,  True])

In [86]:
a[a%2==0]

array([ 6, 16,  4])

In [87]:
#slicing
a=np.arange(4,18)
a

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [88]:
a[1:8:2]

array([ 5,  7,  9, 11])

In [92]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [93]:
a=a+1
a

array([2, 3, 4, 5])

In [94]:
a**2

array([ 4,  9, 16, 25], dtype=int32)

In [95]:
a/2

array([1. , 1.5, 2. , 2.5])

In [96]:
a//2

array([1, 1, 2, 2], dtype=int32)

In [98]:
a

array([2, 3, 4, 5])

In [99]:
a-1

array([1, 2, 3, 4])

In [100]:
b=np.ones((4,))

In [101]:
a

array([2, 3, 4, 5])

In [102]:
b

array([1., 1., 1., 1.])

In [103]:
b=np.ones((5,))+1
b

array([2., 2., 2., 2., 2.])

In [106]:
print(a)
print(b)

[2 3 4 5]
[2. 2. 2. 2. 2.]


In [108]:
b=np.ones((4,))+1
b

array([2., 2., 2., 2.])

In [109]:
a+b

array([4., 5., 6., 7.])

In [110]:
a-b

array([0., 1., 2., 3.])

In [111]:
a*b

array([ 4.,  6.,  8., 10.])

In [112]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[3,2,1],[6,5,4],[9,8,7]])
print(a+b)

[[ 4  4  4]
 [10 10 10]
 [16 16 16]]


In [113]:
print(a*b)

[[ 3  4  3]
 [24 25 24]
 [63 64 63]]


In [114]:
c=np.matmul(a,b)

In [115]:
c

array([[ 42,  36,  30],
       [ 96,  81,  66],
       [150, 126, 102]])

In [116]:
a==b

array([[False,  True, False],
       [False,  True, False],
       [False,  True, False]])

In [117]:
a==c

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [118]:
c>a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [119]:
a>b

array([[False, False,  True],
       [False, False,  True],
       [False, False,  True]])

In [120]:
np.array_equal(a,b)

False

In [121]:
np.array_equal(c,c)

True

In [5]:
#mathematical operation
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [6]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [7]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [8]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [9]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [10]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [11]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])